services:
  clean_architecture-atividade:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - rabbitmq
      - db
    volumes:
      - .:/app
    ports:
      - 8082:8082 # Porta do servidor GraphQL
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres # Configuração do banco de dados
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672/ # URL do RabbitMQ para conexão
  db:
    image: postgres:15
    ports:
      - 5432:5432

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistência dos dados

  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      #Ajustar para variaveis de ambiente
      - 5672:5672 # RabbitMQ
      - 15672:15672 # RabbitMQ Management
      - 15692:15692 
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Armazena os dados do RabbitMQ
      - rabbitmq_conf:/etc/rabbitmq # Armazena a configuração do RabbitMQ

volumes:
  postgres_data:
  rabbitmq_data:
  rabbitmq_conf:
