services:
  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - 5672:5672 # RabbitMQ
      - 15672:15672 # RabbitMQ Management
      - 15692:15692 
    environment:
      - RABBITMQ_DEFAULT_USER=admin 
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/