// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/wrferreira1003/DI/product"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

// Criando uma função para criar uma instancia do usecase
func NewUsecase(db *sql.DB) *product.ProductUsecase {
	productRepository := product.NewProductRepository(db)
	productUsecase := product.NewProductUsecase(productRepository)
	return productUsecase
}

// wire.go:

var setRepository = wire.NewSet(product.NewProductRepository, wire.Bind(new(product.ProductInterface), new(*product.ProductRepository)))
