FROM golang:1.22

# Defina o diretório de trabalho
WORKDIR /go/src/app

# Copie os arquivos do projeto para o diretório de trabalho
COPY . .

# Baixe as dependências do projeto
RUN go mod download

# Compile o projeto
RUN GOOS=linux go build -ldflags "-s -w" -o app

# Defina o comando de inicialização do contêiner
CMD ["./app"]