// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: course_category.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CourseCategory_CreateCategory_FullMethodName = "/pb.CourseCategory/CreateCategory"
)

// CourseCategoryClient is the client API for CourseCategory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Serviço de categoria de curso
type CourseCategoryClient interface {
	// Cria uma nova categoria
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error)
}

type courseCategoryClient struct {
	cc grpc.ClientConnInterface
}

func NewCourseCategoryClient(cc grpc.ClientConnInterface) CourseCategoryClient {
	return &courseCategoryClient{cc}
}

func (c *courseCategoryClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryResponse)
	err := c.cc.Invoke(ctx, CourseCategory_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourseCategoryServer is the server API for CourseCategory service.
// All implementations must embed UnimplementedCourseCategoryServer
// for forward compatibility.
//
// Serviço de categoria de curso
type CourseCategoryServer interface {
	// Cria uma nova categoria
	CreateCategory(context.Context, *CreateCategoryRequest) (*CategoryResponse, error)
	mustEmbedUnimplementedCourseCategoryServer()
}

// UnimplementedCourseCategoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCourseCategoryServer struct{}

func (UnimplementedCourseCategoryServer) CreateCategory(context.Context, *CreateCategoryRequest) (*CategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedCourseCategoryServer) mustEmbedUnimplementedCourseCategoryServer() {}
func (UnimplementedCourseCategoryServer) testEmbeddedByValue()                        {}

// UnsafeCourseCategoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CourseCategoryServer will
// result in compilation errors.
type UnsafeCourseCategoryServer interface {
	mustEmbedUnimplementedCourseCategoryServer()
}

func RegisterCourseCategoryServer(s grpc.ServiceRegistrar, srv CourseCategoryServer) {
	// If the following call pancis, it indicates UnimplementedCourseCategoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CourseCategory_ServiceDesc, srv)
}

func _CourseCategory_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseCategoryServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseCategory_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseCategoryServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CourseCategory_ServiceDesc is the grpc.ServiceDesc for CourseCategory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CourseCategory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CourseCategory",
	HandlerType: (*CourseCategoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCategory",
			Handler:    _CourseCategory_CreateCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "course_category.proto",
}
