### Criando um novo usuário

POST http://localhost:8085/users
Content-Type: application/json

{
  "name": "Luiz",
  "email": "luiz@example.com",
  "password": "123456"
}

### Listando todos os usuários

GET http://localhost:8085/users

### Gerando o token

POST http://localhost:8085/users/generate_token
Content-Type: application/json

{
  "email": "luiz@example.com",
  "password": "123456"
}

