FROM golang:latest as builder

WORKDIR /app
COPY . .
# DWARF - Debugging With Arbytrary record format - Formato de registro arbitrário para depuração
# -w -s -> Remove informações de depuração e símbolos
# CGO_ENABLED=0 -> Desabilita a comunicação com o sistema operacional caso seja necessário
RUN GOOS=linux CGO_ENABLED=0 go build -ldflags="-w -s" -o server .

FROM scratch
COPY --from=builder /app/server .
CMD ["./server"]

